
export const categories =
    [
        [
            {
                id: 1,
                cat_name: "Trang điểm",
                slug: "trang-diem",
                parent_id: 0,
                type: 0,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: "2022-06-24T07:28:20.000000Z",
                deleted_at: null
            },
            {
                id: 2,
                cat_name: "Chăm sóc da",
                slug: "cham-soc-da",
                parent_id: 0,
                type: 0,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 3,
                cat_name: "Chăm sóc tóc",
                slug: "cham-soc-toc",
                parent_id: 0,
                type: 0,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 4,
                cat_name: "Chăm sóc toàn thân",
                slug: "cham-soc-toan-than",
                parent_id: 0,
                type: 0,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 5,
                cat_name: "Phụ kiện",
                slug: "phu-kien",
                parent_id: 0,
                type: 0,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 6,
                cat_name: "Nước hoa",
                slug: "nuoc-hoa",
                parent_id: 0,
                type: 0,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            }
        ],
        [
            {
                id: 7,
                cat_name: "Trang điểm mặt",
                slug: "trang-diem-mat-face",
                parent_id: 1,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 8,
                cat_name: "Trang điểm mắt",
                slug: "trang-diem-mat-eye",
                parent_id: 1,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 9,
                cat_name: "Trang điểm môi",
                slug: "trang-diem-moi",
                parent_id: 1,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 10,
                cat_name: "Dưỡng da",
                slug: "duong-da",
                parent_id: 2,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 11,
                cat_name: "Làm sạch da",
                slug: "lam-sach-da",
                parent_id: 2,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 12,
                cat_name: "Mặt nạ",
                slug: "mat-na",
                parent_id: 2,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 13,
                cat_name: "Chăm sóc chuyên sâu",
                slug: "cham-soc-chuyen-sau",
                parent_id: 2,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 14,
                cat_name: "Dưỡng tóc",
                slug: "duong-toc",
                parent_id: 3,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 15,
                cat_name: "Tạo kiểu tóc",
                slug: "tao-kieu-toc",
                parent_id: 3,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 16,
                cat_name: "Dưỡng thể",
                slug: "duong-the",
                parent_id: 4,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 17,
                cat_name: "Làm sạch cơ thể",
                slug: "lam-sach-co-the",
                parent_id: 4,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 18,
                cat_name: "Dưỡng móng tay",
                slug: "duong-mong-tay",
                parent_id: 4,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 19,
                cat_name: "Dành cho mặt",
                slug: "danh-cho-mat",
                parent_id: 5,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 20,
                cat_name: "Dụng cụ trang điểm",
                slug: "dung-cu-trang-diem",
                parent_id: 5,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 21,
                cat_name: "Nước hoa toàn thân",
                slug: "nuoc-hoa-toan-than",
                parent_id: 6,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 71,
                cat_name: "Cây Lược 57 d",
                slug: "cay-luoc-57-d",
                parent_id: 3,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-06-10T17:30:33.000000Z",
                updated_at: "2022-06-11T08:59:28.000000Z",
                deleted_at: null
            },
            {
                id: 72,
                cat_name: "mua sam",
                slug: "mua-sam",
                parent_id: 1,
                type: 1,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-06-14T10:11:02.000000Z",
                updated_at: "2022-06-27T02:43:31.000000Z",
                deleted_at: null
            }
        ],
        [
            {
                id: 22,
                cat_name: "Kem nền - Bảng phấn nền",
                slug: "kem-nen-bang-phan-nen",
                parent_id: 7,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 23,
                cat_name: "Phấn phủ",
                slug: "phan-phu",
                parent_id: 7,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 24,
                cat_name: "Phấn má hồng",
                slug: "phan-ma-hong",
                parent_id: 7,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 25,
                cat_name: "Kem lót - Primer",
                slug: "kem-lot-primer",
                parent_id: 7,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 26,
                cat_name: "Kem che khuyết điểm",
                slug: "kem-che-khuyet-diem",
                parent_id: 7,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 27,
                cat_name: "Phấn tạo khối",
                slug: "phan-tao-khoi",
                parent_id: 7,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 28,
                cat_name: "Kem nền BB & CC",
                slug: "kem-nen-bb-&-cc",
                parent_id: 7,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 29,
                cat_name: "Phấn mắt",
                slug: "phan-mat",
                parent_id: 8,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 30,
                cat_name: "Bút kẻ mắt",
                slug: "but-ke-mat",
                parent_id: 8,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 31,
                cat_name: "Mascara",
                slug: "mascara",
                parent_id: 8,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 32,
                cat_name: "Bút kẻ chân mày",
                slug: "but-ke-chan-may",
                parent_id: 8,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 33,
                cat_name: "Son môi",
                slug: "son-moi",
                parent_id: 9,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 34,
                cat_name: "Son dưỡng",
                slug: "son-duong",
                parent_id: 9,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 35,
                cat_name: "Lips Mask - Mặt nạ môi",
                slug: "lips-mask-mat-na-moi",
                parent_id: 9,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 36,
                cat_name: "Kem dưỡng ẩm",
                slug: "kem-duong-am",
                parent_id: 10,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 37,
                cat_name: "Xịt dưỡng - Xịt khoáng",
                slug: "xit-duong-xit-khoang",
                parent_id: 10,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 38,
                cat_name: "Kem chống nắng",
                slug: "kem-chong-nang",
                parent_id: 10,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 39,
                cat_name: "Gel dưỡng",
                slug: "gel-duong",
                parent_id: 10,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 40,
                cat_name: "Tẩy trang",
                slug: "tay-trang",
                parent_id: 11,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 41,
                cat_name: "Sữa rửa mặt",
                slug: "sua-rua-mat",
                parent_id: 11,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 42,
                cat_name: "Khăn - Bông tẩy trang",
                slug: "khan-bong-tay-trang",
                parent_id: 11,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 43,
                cat_name: "Mặt nạ giấy",
                slug: "mat-na-giay",
                parent_id: 12,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 44,
                cat_name: "Mặt nạ ngủ",
                slug: "mat-na-ngu",
                parent_id: 12,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 45,
                cat_name: "Mặt nạ rửa",
                slug: "mat-na-rua",
                parent_id: 12,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 46,
                cat_name: "Mặt nạ dưỡng môi",
                slug: "mat-na-duong-moi",
                parent_id: 12,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 47,
                cat_name: "Mặt nạ đất sét",
                slug: "mat-na-dat-set",
                parent_id: 12,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 48,
                cat_name: "Serum dưỡng da",
                slug: "serum-duong-da",
                parent_id: 13,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 49,
                cat_name: "Nước cân bằng",
                slug: "nuoc-can-bang",
                parent_id: 13,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 50,
                cat_name: "Đặc trị mụn",
                slug: "dac-tri-mun",
                parent_id: 13,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 51,
                cat_name: "Tinh chất",
                slug: "tinh-chat",
                parent_id: 13,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 52,
                cat_name: "Tẩy tế bào chết",
                slug: "tay-te-bao-chet",
                parent_id: 13,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 53,
                cat_name: "Toner - Lotion",
                slug: "toner-lotion",
                parent_id: 13,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 54,
                cat_name: "Serum dưỡng tóc",
                slug: "serum-duong-toc",
                parent_id: 14,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 55,
                cat_name: "Dầu gội",
                slug: "dau-goi",
                parent_id: 14,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 56,
                cat_name: "Dầu xã",
                slug: "dau-xa",
                parent_id: 14,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 57,
                cat_name: "Dầu gội khô",
                slug: "dau-goi-kho",
                parent_id: 14,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 58,
                cat_name: "Keo xịt tóc",
                slug: "keo-xit-toc",
                parent_id: 15,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 59,
                cat_name: "Sữa dưỡng thể",
                slug: "sua-duong-the",
                parent_id: 16,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 60,
                cat_name: "Kem dưỡng tay",
                slug: "kem-duong-tay",
                parent_id: 16,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 61,
                cat_name: "Tẩy tế bào chết toàn thân",
                slug: "tay-te-bao-chet-toan-than",
                parent_id: 17,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 62,
                cat_name: "Nước rửa tay",
                slug: "nuoc-rua-tay",
                parent_id: 17,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 63,
                cat_name: "Sữa tắm",
                slug: "sua-tam",
                parent_id: 17,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 64,
                cat_name: "Sơn móng tay",
                slug: "son-mong-tay",
                parent_id: 18,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 65,
                cat_name: "Dụng cụ chăm sóc mặt",
                slug: "dung-cu-cham-soc-mat",
                parent_id: 19,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 66,
                cat_name: "Cọ nền",
                slug: "co-nen",
                parent_id: 20,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 67,
                cat_name: "Uốn mi",
                slug: "uon-mi",
                parent_id: 20,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 68,
                cat_name: "Giấy thấm dầu",
                slug: "giay-tham-dau",
                parent_id: 20,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 69,
                cat_name: "Nước hoa cơ thể",
                slug: "nuoc-hoa-co-the",
                parent_id: 21,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            },
            {
                id: 70,
                cat_name: "Tinh dầu nước hoa",
                slug: "tinh-dau-nuoc-hoa",
                parent_id: 21,
                type: 2,
                author: "Admin",
                trash: 0,
                status: 1,
                created_at: "2022-04-09T16:09:21.000000Z",
                updated_at: null,
                deleted_at: null
            }
        ]
    ]